[project]
name = "booksharing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.18.4",
    "asyncpg>=0.31.0",
    "fastapi>=0.136.3",
    "greenlet>=3.5.1",
    "passlib[bcrypt]>=1.7.4",
    "pydantic[email]>=2.13.4",
    "pydantic-settings>=2.14.1",
    "pyjwt>=2.13.0",
    "sqlalchemy>=2.0.50",
    "uvicorn>=0.49.0",
    "python-multipart>=0.0.32",
    "starlette-admin[sql,sqla]>=0.16.1",
    "sqlmodel>=0.0.39",
    "itsdangerous>=2.2.0",
]
