"""add password and refresh

Revision ID: 262d82fe08f3
Revises: 91a47ad459a1
Create Date: 2026-06-11 10:17:05.377688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '262d82fe08f3'
down_revision: Union[str, Sequence[str], None] = '91a47ad459a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=False, server_default=''))
    op.add_column('users', sa.Column('refresh_token', sa.String(), nullable=True))
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'])
    op.create_unique_constraint(op.f('uq_users_username'), 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_username'), 'users', type_='unique')
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.drop_column('users', 'refresh_token')
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
