"""Add field cover_url

Revision ID: 72df8e42389a
Revises: 65949bef5ce8
Create Date: 2026-06-30 06:47:48.546446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72df8e42389a'
down_revision: Union[str, Sequence[str], None] = '65949bef5ce8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('cover_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'cover_url')
    # ### end Alembic commands ###
