"""Add relationship

Revision ID: f32d9b375508
Revises: a526a7ca77d7
Create Date: 2026-06-23 07:05:31.902028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f32d9b375508'
down_revision: Union[str, Sequence[str], None] = 'a526a7ca77d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(op.f('fk_books_user_id_users'), 'books', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_books_user_id_users'), 'books', type_='foreignkey')
    op.drop_column('books', 'user_id')
    # ### end Alembic commands ###
